services:

  services:
    image: pabgarsi/hotels-services:latest
    mem_limit: 800m
    ports:
      - "8080:8080"
    networks:
      - pabgarsi-network
    
  reviews:
    image: pabgarsi/reviews:latest
    mem_limit: 800m
    ports:
      - "8081:8081"
    networks:
      - pabgarsi-network
  
  hotels:
    image: pabgarsi/hotelslist:latest
    mem_limit: 800m
    ports:
      - "8082:8082"
    networks:
      - pabgarsi-network
    
networks:
  pabgarsi-network: